FROM ubuntu:18.04 AS netcomp_server

RUN apt-get update -y && apt-get upgrade -y

# Install memcached
RUN apt-get install -y memcached iproute2 net-tools tcpdump

WORKDIR /opt/bmc-cache

# Expose port for external communication
EXPOSE 11211/tcp
EXPOSE 11211/udp

# Default command (can be overridden)
# memcached -u root -m 1024 -p 11211 -U 11211 -vv
CMD ["memcached", "-u", "root", "-m", "1024", "-p", "11211", "-U", "11211", "-vv"]